bno055:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "uart"
    uart_port: "/dev/imu"
    uart_baudrate: 115200
    uart_timeout: 0.1
    data_query_frequency: 100
    calib_status_frequency: 10.0
    frame_id: "bno055"
    operation_mode: 0x0C
    placement_axis_remap: "P2"
    acc_factor: 100.0
    mag_factor: 16000000.0
    gyr_factor: 900.0
    grav_factor: 100.0

    set_offsets: true

    # Offset từ calibration_request
    offset_acc: [24, 21, 65498]
    offset_mag: [269, 35, 65257]
    offset_gyr: [1, 4, 65535]

    # Ma trận hiệp phương sai (Covariance)
    variance_acc: [0.03, 0.03, 0.03]            # Đơn vị: m/s²
    variance_angular_vel: [0.01, 0.01, 0.01]    # Đơn vị: rad/s
    variance_orientation: [0.0159, 0.0159, 0.0159]  # Đơn vị: rad
    variance_mag: [0.1, 0.1, 0.1]               # Đơn vị: Tesla

