collision_monitor:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel"
    cmd_vel_out_topic: "cmd_vel_dk"
    transform_tolerance: 0.5
    source_timeout: 5.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    polygons: ["PolygonStop"]
    PolygonStop:
      type: "polygon"
      points: [0.9, 0.3, 0.9, -0.3, 0.5, -0.3, 0.5, 0.3]
      action_type: "stop"
      max_points: 1
      visualize: True
      polygon_pub_topic: "polygon_stop"
      enabled: True
 
#    PolygonSlow:
#      type: "polygon"
#      points: [0.4, 0.4, 0.4, -0.4, -0.4, -0.4, -0.4, 0.4]
#      action_type: "slowdown"
#      max_points: 3
#      slowdown_ratio: 0.3
#      visualize: True
#      polygon_pub_topic: "polygon_slowdown"
#      enabled: True
#    FootprintApproach:
#      type: "polygon"
#      action_type: "approach"
#      footprint_topic: "/local_costmap/published_footprint"
#      time_before_collision: 2.0
#      simulation_time_step: 0.1
#      max_points: 5
#      visualize: False
#      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
      enabled: True
#    pointcloud:
#      type: "pointcloud"
#      topic: "/intel_realsense_r200_depth/points"
#      min_height: 0.1
#      max_height: 0.5
#      enabled: True
